### ISSUE TITLE
llama3_encoder has different behaviors from transformers's llama3 tokennizer

### ISSUE THREAD

**Issue by WhatGhost** [gh-markt/cpp-tiktoken#12]
@gh-markt 
i try to use your lib to do tokenizer for llama3.1 model

But the ids after tokennizer is different

here is my code

```
int main() {
    auto encoder = GptEncoding::get_encoding_llama3(LanguageModel::CL100K_BASE);
    std::string string_to_encode = "请你基于以下「评估标准」";
    auto tokens = encoder->encode(string_to_encode);


    std::cout << "Encoded tokens: ";
    std::cout << tokens.size() << std::endl;
    for (auto token : tokens) {
        std::cout << token<< " ";
    }
    std::cout << std::endl;
}
```

and the result is 
[15225 57668 75146 35304 88852 13177 64479 17885 108 31944 12870 228 10646]

but when i use python's transformers lib to do the tokennize for the same input,the ids is
[15225, 57668, 125510, 88852, 13177, 64479, 112494, 110778, 10646]

I also use a llama3-tokennizer web demo to check the reslut (https://github.com/belladoreai/llama3-tokenizer-js/tree/master)
the result ids is same to transformers.

I wonder if there is any differnet betwen these?And how can i solve this problem.

Thanks!

**Comment by gh-markt** [comment]
All of the llama3 support in this project was added by another contributor,
whose branch can be found at

https://github.com/nguyenhoangthuan99/cpp-tiktoken

**Comment by gh-markt** [comment]
@nguyenhoangthuan99 Be advised that there are some stability issues with these changes,

in particular the TestLLama3Tokenizer test does not complete successfully, and an issue has been reported on my project that is probably reflective of this.

Note also that your the latest master of my branch will have to be merged with yours or else the tests.cpp file will not link, as it is missing the fmt library..

**Comment by nguyenhoangthuan99** [comment]
@gh-markt you are right, the fmt lib is not handle properly in my side, I have updated it in this pr #13, seem like fmt is not necessary. I also submodule to pcre2 and build it along with the project, so pcre2 is not required to install externelly.

Hi @WhatGhost , llama3.1 has a small change on tokenizer and I think you should use the tokenizer for llama3.1 in this [test](https://github.com/gh-markt/cpp-tiktoken/pull/13/files#diff-93213ad7b936575f157c5eec70f90b2524df0bc53244509816ae136a565fb3b8) .
I write this test for your case and it can pass.

**Comment by gh-markt** [comment]
Thank you again @nguyenhoangthuan99.  The tests now all pass correctly.

**Comment by WhatGhost** [comment]
@nguyenhoangthuan99 @gh-markt Thanks for your reply. It works!
