### ISSUE TITLE
Usage in commercial project

### ISSUE THREAD

**Issue by tagyro** [gh-markt/cpp-tiktoken#3]
Can't really make it out from the License - am I allowed to use this in a commercial project?

**Comment by gh-markt** [comment]
Yes, you most certainly are.   The License.md file contains information on the provisions for redistribution.

Thanks for your interest.

**Comment by tagyro** [comment]
I am writing an Objective-C (++) wrapper for this so I won't be using other projects and I will, of course, include the License in the project.
Thank you for the library!

**Comment by gh-markt** [comment]
I would encourage you to use the most recent version of the library and not any prior versions that other projects use, since there have been some design bugs that were fixed, which were not a problem with how some projects might have used this library previously.
