### ISSUE TITLE
Error: undefined reference to pcre2_*_8

### ISSUE THREAD

**Issue by mandarddixit** [gh-markt/cpp-tiktoken#4]
I try to compile a very simple code using your library and I get the following errors:

/usr/bin/ld: /home/mandar/cpp-tiktoken//lib/libtiktoken.a(pcre2_regex.cc.o): in function `PCRERegex::PCRERegex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
pcre2_regex.cc:(.text+0xb3): undefined reference to `pcre2_compile_8'
/usr/bin/ld: pcre2_regex.cc:(.text+0xe8): undefined reference to `pcre2_get_error_message_8'
/usr/bin/ld: /home/mandar/cpp-tiktoken//lib/libtiktoken.a(pcre2_regex.cc.o): in function `PCRERegex::~PCRERegex()':
pcre2_regex.cc:(.text+0x1e5): undefined reference to `pcre2_code_free_8'
/usr/bin/ld: /home/mandar/cpp-tiktoken//lib/libtiktoken.a(pcre2_regex.cc.o): in function `PCRERegex::all_matches(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
pcre2_regex.cc:(.text+0x69a): undefined reference to `pcre2_match_data_create_from_pattern_8'
/usr/bin/ld: pcre2_regex.cc:(.text+0x6d5): undefined reference to `pcre2_match_8'
/usr/bin/ld: pcre2_regex.cc:(.text+0x6ee): undefined reference to `pcre2_get_ovector_pointer_8'
/usr/bin/ld: pcre2_regex.cc:(.text+0x75c): undefined reference to `pcre2_match_data_free_8'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/main.dir/build.make:113: main] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

Any idea what these are ? how to fix them?

**Comment by mandarddixit** [comment]
I started over with the original CMakeLists.txt. When I run cmake, the find_package line is unable to locate PCRE2:

Command: 
cmake -DCMAKE_PREFIX_PATH="${HOME}/pcre2-10.42/" ..

Output: 
**-- Could NOT find PCRE2 (missing: PCRE2_DIR)**
-- Copying tokenizers to '/home/mandar/cpp-tiktoken/build/tokenizers'.
-- Tokenizers copied.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mandar/cpp-tiktoken/build

I the try to compile my code (a few lines cpp) using the following CmakeLists.txt

======================================
cmake_minimum_required(VERSION` 3.10 FATAL_ERROR)
project(example LANGUAGES CXX)

set(TIKTOKEN_CPP_DIR "/home/mandar/cpp-tiktoken/")

find_package(Torch REQUIRED)

if(Torch_FOUND)
        message("Torch Found")
elseif(NOT Torch_FOUND)
    error("Torch Not Found")
endif()

add_executable(main main.cpp)
target_link_libraries(main ${TORCH_LIBRARIES} "${TIKTOKEN_CPP_DIR}/libtiktoken.a")
target_include_directories(main PUBLIC ${TORCH_INCLUDE_DIRS} ${TIKTOKEN_CPP_DIR})
set_property(TARGET main PROPERTY CXX_STANDARD 14)**
=======================================

Running "make" gives the following error:

[ 50%] Building CXX object CMakeFiles/main.dir/main.cpp.o
[100%] Linking CXX executable main
/usr/bin/ld: CMakeFiles/main.dir/main.cpp.o: in function `main':
main.cpp:(.text+0x25f): undefined reference to `GptEncoding::encode(std::string const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&)'
/usr/bin/ld: /home/mandar/cpp-tiktoken//libtiktoken.a(pcre2_regex.cc.o): in function `PCRERegex::PCRERegex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
pcre2_regex.cc:(.text+0xb3): undefined reference to `pcre2_compile_8'
/usr/bin/ld: pcre2_regex.cc:(.text+0xe8): undefined reference to `pcre2_get_error_message_8'
/usr/bin/ld: /home/mandar/cpp-tiktoken//libtiktoken.a(pcre2_regex.cc.o): in function `PCRERegex::~PCRERegex()':
pcre2_regex.cc:(.text+0x1e5): undefined reference to `pcre2_code_free_8'
/usr/bin/ld: /home/mandar/cpp-tiktoken//libtiktoken.a(pcre2_regex.cc.o): in function `PCRERegex::all_matches(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
pcre2_regex.cc:(.text+0x69a): undefined reference to `pcre2_match_data_create_from_pattern_8'
/usr/bin/ld: pcre2_regex.cc:(.text+0x6d5): undefined reference to `pcre2_match_8'
/usr/bin/ld: pcre2_regex.cc:(.text+0x6ee): undefined reference to `pcre2_get_ovector_pointer_8'
/usr/bin/ld: pcre2_regex.cc:(.text+0x75c): undefined reference to `pcre2_match_data_free_8'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/main.dir/build.make:113: main] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by gh-markt** [comment]
What project are you using that has that code?

What you've typed above is not from my project

**Comment by mandarddixit** [comment]
Just a simple cpp file building on top of your library:

#include <iostream>
#include <string>
#include <vector>
#include "encoding.h"
#include "modelparams.h"
#include "pcre2_regex.h"
#include <torch/torch.h>

using namespace std;

int main()
{
    torch::Tensor tensor = torch::zeros({2, 2});
    std::cout << tensor << std::endl;


    LanguageModel model = LanguageModel::CL100K_BASE;

    auto encoder = GptEncoding::get_encoding(model);

    std::string input = "test";

    std::cout << encoder->encode(input)[0] << std::endl;


    return 0;
}

**Comment by gh-markt** [comment]
You need to include pcre2-8 in your target link libraries

**Comment by mandarddixit** [comment]
It did work to fix that error. Thank you.

But I am getting a new one upon running make

Consolidate compiler generated dependencies of target main
[ 50%] Building CXX object CMakeFiles/main.dir/main.cpp.o
[100%] Linking CXX executable main
/usr/bin/ld: CMakeFiles/main.dir/main.cpp.o: in function `main':
main.cpp:(.text+0x1d3): undefined reference to `GptEncoding::encode(std::string const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/main.dir/build.make:114: main] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:91: all] Error 2


My code again is a simple few lines, following

```
#include <iostream>
#include <string>
#include <vector>
#include "encoding.h"
#include "modelparams.h"
#include "pcre2_regex.h"
#include <torch/torch.h>

using namespace std;

int main()
{

    LanguageModel model = LanguageModel::CL100K_BASE;

    auto encoder = GptEncoding::get_encoding(model);

    unordered_set<string> allowed_special = {};
    unordered_set<string> disallowed_special = {"all"};

    vector<int> tokens = encoder->encode("test", allowed_special, disallowed_special);

    std::cout << tokens[0] << std::endl;


    return 0;
}

```

I am able to compile if the code stops at get_encoding(model). It throws an error when I ask the encoder to ->encode(). Any idea what I am missing?

**Comment by mandarddixit** [comment]
Ok I figured torch was messing something up. When I don't link ${TORCH_LIBRARIES} to my project, the code compiles and your functions produce desired output.
